repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["."]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        pass_filenames: false
        always_run: true
        args: ["."]
