site_name: Agent Lightning
site_url: https://microsoft.github.io/agent-lightning/
repo_url: https://github.com/microsoft/agent-lightning
repo_name: agent-lightning

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: latest

extra:
  version:
    provider: mike
    default: latest

nav:
  - Home: index.md
  - Quickstart:
    - Installation: quickstart/installation.md
    - Getting Started: quickstart/getting-started.md
  - How-To:
    - Basic Usage: how-to/basic-usage.md
    - Advanced Features: how-to/advanced-features.md
  - Deep Dive:
    - Architecture: deep-dive/architecture.md
    - Concepts: deep-dive/concepts.md
  - API Reference:
    - Core: reference/core.md
    - RL: reference/rl.md
