apiVersion: apps/v1
kind: Deployment
metadata:
  name: agl-controller
  labels:
    app: agl-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agl-controller
  template:
    metadata:
      labels:
        app: agl-controller
    spec:
      serviceAccountName: agl-controller
      containers:
        - name: controller
          image: agl-lite:dev
          imagePullPolicy: Never
          command:
            - "agl-lite"
            - "controller"
            - "--agl-lite-url"
            - "$(AGL_LITE_URL)"
            - "--namespace"
            - "$(AGL_K8S_NAMESPACE)"
            - "--secret-name"
            - "$(AGL_SECRET_NAME)"
          env:
            - name: AGL_KEY
              valueFrom:
                secretKeyRef:
                  name: agl-lite-keys
                  key: AGL_KEY
            - name: AGL_LITE_URL
              valueFrom:
                configMapKeyRef:
                  name: agl-lite-config
                  key: AGL_LITE_URL
            - name: AGL_K8S_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: agl-lite-config
                  key: AGL_K8S_NAMESPACE
            - name: AGL_SECRET_NAME
              valueFrom:
                configMapKeyRef:
                  name: agl-lite-config
                  key: AGL_SECRET_NAME
            - name: AGL_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: agl-lite-config
                  key: AGL_POLL_INTERVAL
            - name: AGL_MAX_QUEUE_TIME
              valueFrom:
                configMapKeyRef:
                  name: agl-lite-config
                  key: AGL_MAX_QUEUE_TIME
