apiVersion: v1
kind: ServiceAccount
metadata:
  name: agl-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agl-controller-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agl-controller-binding
subjects:
  - kind: ServiceAccount
    name: agl-controller
roleRef:
  kind: Role
  name: agl-controller-role
  apiGroup: rbac.authorization.k8s.io
