hydra:
  searchpath:
    - pkg://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

agentlightning:
  agl_base_url: ${oc.env:AGL_BASE_URL,http://localhost:8080}
  agl_key: ${oc.env:AGL_KEY,}
  model_endpoint: ${oc.env:AGL_MODEL_ENDPOINT,}  # external model endpoint (if not using VERL's internal vLLM)
  timeout_seconds: 1200
  trace_aggregator:
    level: transition
    trajectory_max_prompt_length: 2048
    trajectory_max_response_length: 8192
    debug: False
    mismatch_log_dir: ./mismatch_cases

data:
  filter_overlong_prompts: false

actor_rollout_ref:
  rollout:
    mode: async
