#!/bin/bash
# Run the Calc-X VERL training end-to-end.
#
# Usage:
#   examples/calc_x/run.sh                     # full training
#   examples/calc_x/run.sh --ci-fast           # single PPO step
#
# Topology (agl-in-host mode):
#   Host:     agl-lite serve + vLLM inference
#   Minikube: controller + agent pods (AutoGen + MCP calculator)
#
# Prerequisites:
#   - minikube running
#   - AGL_KEY set in environment
#   - vLLM serving on host (scripts/start_vllm.sh)
#   - Calc-X dataset downloaded to examples/calc_x/data/
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MODE_DIR="$SCRIPT_DIR"

cd "$REPO_ROOT"

# --- Setup log directory ---
LOG_DIR="$SCRIPT_DIR/logs/$(date +%Y%m%d-%H%M%S)"
mkdir -p "$LOG_DIR/agents"
export AGL_LOG_DIR="$LOG_DIR"
echo "=== Logs → $LOG_DIR ==="

# --- Mount agent log directory into minikube ---
# Agent pods write to hostPath /tmp/agl-lite/logs inside minikube VM.
# minikube mount bridges that to the host filesystem so logs survive pod deletion.
MOUNT_SRC="$LOG_DIR/agents"
MOUNT_DST="/tmp/agl-lite/logs"
echo "=== Mounting $MOUNT_SRC → minikube:$MOUNT_DST ==="
minikube mount "$MOUNT_SRC:$MOUNT_DST" &
MOUNT_PID=$!
sleep 2
if ! kill -0 $MOUNT_PID 2>/dev/null; then
    echo "ERROR: minikube mount failed"
    exit 1
fi
trap 'kill $MOUNT_PID 2>/dev/null; wait $MOUNT_PID 2>/dev/null' EXIT

# --- Load config ---
if [ ! -f "$MODE_DIR/.env.example" ]; then
    echo "ERROR: $MODE_DIR/.env.example not found"
    exit 1
fi
source "$MODE_DIR/.env.example"
DEPLOY_CONFIG="$MODE_DIR/.env.example"

# --- Validate AGL_KEY ---
# AGL_KEY can come from: (1) environment, (2) state file from previous deploy.
STATE_ENV=".local/agl-lite.env"
if [ -z "${AGL_KEY:-}" ] && [ -f "$STATE_ENV" ]; then
    echo "=== Loading AGL_KEY from $STATE_ENV ==="
    source "$STATE_ENV"
fi
if [ -z "${AGL_KEY:-}" ]; then
    echo "ERROR: AGL_KEY not set. Either:"
    echo "  export AGL_KEY=\$(openssl rand -hex 32)"
    echo "  or run 'agl-lite deploy' first (stores key in $STATE_ENV)"
    exit 1
fi

# Note: vLLM is managed internally by VERL (hybrid mode), not started externally.
# The AglLiteAgentLoopManager registers VERL's vLLM server addresses with the
# agl-lite gateway at runtime.

# --- Build images ---
echo ""
echo "=== Building images ==="
scripts/build_images.sh --include-example calc_x

# --- Deploy K8s infra + start host agl-lite ---
NS="$(grep -E '^AGL_NAMESPACE=' "$DEPLOY_CONFIG" | cut -d= -f2 | tr -d '[:space:]')"
echo ""
# Clean up previous deployment if any — avoids stale Jobs/pods from prior runs.
if kubectl get namespace "$NS" > /dev/null 2>&1; then
    echo "=== Cleaning up previous deployment in namespace: $NS ==="
    uv run agl-lite deploy --env-file "$DEPLOY_CONFIG" --cleanup
fi
echo "=== Deploying (agl-in-host) ==="
uv run agl-lite deploy --env-file "$DEPLOY_CONFIG"

# --- Wait for agl-lite ---
echo ""
echo "=== Waiting for agl-lite ==="
READY=false
for i in $(seq 1 40); do
    if curl -sf http://localhost:8080/healthz > /dev/null 2>&1; then
        echo "  agl-lite ready"
        READY=true
        break
    fi
    sleep 1
done
if [ "$READY" != true ]; then
    echo "ERROR: agl-lite did not become ready"
    exit 1
fi

# --- Export env for training script ---
# Source the state file generated by deploy (has AGL_KEY, AGL_BASE_URL).
if [ -f "$STATE_ENV" ]; then
    source "$STATE_ENV"
fi
export AGL_BASE_URL=${AGL_BASE_URL:-http://localhost:8080}
export AGL_KEY

# Avoid conflicts with existing Ray clusters on shared machines.
export RAY_GCS_SERVER_PORT=${RAY_GCS_SERVER_PORT:-0}
export RAY_tmpdir=${RAY_tmpdir:-/tmp/ray_agl_lite_$$}

# Clean up any leftover Ray processes from previous runs.
.venv/bin/ray stop --force 2>/dev/null || true

# --- Run training ---
# Training output goes to both stdout and a log file in the run's log directory.
echo ""
echo "=== Running VERL training ==="
echo "  Training log: $LOG_DIR/training.log"
echo "  Server log:   $LOG_DIR/server.log"
exec .venv/bin/python examples/calc_x/train_calc_agent.py \
    --train-file "${AGL_TRAIN_FILE:-examples/calc_x/data/train.parquet}" \
    --val-file "${AGL_VAL_FILE:-examples/calc_x/data/test.parquet}" \
    "$@" \
    2>&1 | tee "$LOG_DIR/training.log"
