# Copyright (c) Microsoft. All rights reserved.

from __future__ import annotations

import warnings
from importlib import import_module
from typing import Any, Callable, Type, cast

__all__ = [
    "instrument_vllm",
    "uninstrument_vllm",
]

_original_chat_completion_full_generator: Callable[..., Any] | None = None
_patched_response_cls: Type[Any] | None = None


def _load_vllm_targets() -> tuple[Any, Type[Any], Type[Any]]:
    """Load vLLM objects only when vLLM instrumentation is requested."""
    protocol = import_module("vllm.entrypoints.openai.protocol")
    serving_chat = import_module("vllm.entrypoints.openai.serving_chat")
    response_cls = cast(Type[Any], getattr(protocol, "ChatCompletionResponse"))
    serving_chat_cls = cast(Type[Any], getattr(serving_chat, "OpenAIServingChat"))
    return protocol, response_cls, serving_chat_cls


def _make_patched_response_cls(base_cls: Type[Any]) -> Type[Any]:
    return type(
        "ChatCompletionResponsePatched",
        (base_cls,),
        {
            "__annotations__": {
                "prompt_token_ids": list[int] | None,
                "response_token_ids": list[list[int]] | None,
            },
            "prompt_token_ids": None,
            "response_token_ids": None,
            "__module__": __name__,
        },
    )


async def chat_completion_full_generator(
    self: Any,
    request: Any,
    result_generator: Any,
    request_id: str,
    model_name: str,
    conversation: Any,
    tokenizer: Any,
    request_metadata: Any,
) -> Any:
    if _original_chat_completion_full_generator is None:
        raise RuntimeError("vLLM instrumentation has not been initialized.")

    prompt_token_ids: list[int] | None = None
    response_token_ids: list[list[int]] | None = None

    async def _generate_inceptor() -> Any:
        nonlocal prompt_token_ids, response_token_ids
        async for res in result_generator:
            yield res
            prompt_token_ids = res.prompt_token_ids
            response_token_ids = [output.token_ids for output in res.outputs]

    response = await _original_chat_completion_full_generator(
        self,
        request,
        _generate_inceptor(),
        request_id,
        model_name,
        conversation,
        tokenizer,
        request_metadata,
    )
    return response.model_copy(
        update={
            "prompt_token_ids": prompt_token_ids,
            "response_token_ids": response_token_ids,
        }
    )


def instrument_vllm() -> None:
    """Instrument vLLM to capture token IDs generated by engine.

    This instrumentation has been merged to upstream vLLM since v0.10.2.
    """
    global _original_chat_completion_full_generator, _patched_response_cls

    protocol, response_cls, serving_chat_cls = _load_vllm_targets()
    if _patched_response_cls is not None and response_cls is _patched_response_cls:
        warnings.warn("vllm is already instrumented. Skip the instrumentation.")
        return

    _patched_response_cls = _make_patched_response_cls(response_cls)
    if _original_chat_completion_full_generator is None:
        _original_chat_completion_full_generator = cast(
            Callable[..., Any], serving_chat_cls.chat_completion_full_generator
        )

    protocol.ChatCompletionResponse = _patched_response_cls
    serving_chat_cls.chat_completion_full_generator = chat_completion_full_generator


def uninstrument_vllm() -> None:
    """Uninstrument vLLM to stop capturing token IDs generated by engine."""
    global _patched_response_cls

    protocol, response_cls, serving_chat_cls = _load_vllm_targets()
    if _patched_response_cls is not None and response_cls is _patched_response_cls:
        # Use the patched class' first base, which is the original ChatCompletionResponse.
        protocol.ChatCompletionResponse = _patched_response_cls.__bases__[0]
    if _original_chat_completion_full_generator is not None:
        serving_chat_cls.chat_completion_full_generator = _original_chat_completion_full_generator
    _patched_response_cls = None
