name: Badge - Unsloth

on:
  workflow_run:
    workflows:
      - Examples - Unsloth
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Skip non-main runs
        if: ${{ github.event.workflow_run.head_branch != 'main' }}
        run: echo "Skipping because branch '${{ github.event.workflow_run.head_branch }}' is not main."

      - name: Verify stable variant
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runId = context.payload.workflow_run.id;
            const attempt = context.payload.workflow_run.run_attempt ?? 1;

            const { data } = await github.rest.actions.listJobsForWorkflowRunAttempt({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
              attempt_number: attempt,
              per_page: 100,
            });

            const jobs = data.jobs ?? [];
            const job = jobs.find(job => job.name.toLowerCase().includes(', stable)'));

            if (!job) {
              core.setFailed('Missing stable variant job.');
              return;
            }

            core.info(`${job.name} => ${job.conclusion}`);

            if (job.conclusion !== 'success') {
              core.setFailed(`${job.name} concluded ${job.conclusion}`);
            }
