name: GPU Test
permissions:
  contents: read
on:
  schedule:
    # Every day at 3 AM UTC+8
    - cron: '0 19 * * *'

  workflow_dispatch:

jobs:
  examples:
    runs-on: [self-hosted, 1ES.Pool=agl-runner-gpu]
    timeout-minutes: 60
    steps:
      - name: Check GPU status
        run: nvidia-smi
      - uses: actions/checkout@v4
      - name: Create a virtual environment
        run: python3 -m venv .venv
