name: GPU Test
permissions:
  contents: read
on:
  push:  # for debugging purposes
    branches: [examples-test]
  schedule:
    # Every day at 4 AM UTC+8
    - cron: '0 20 * * *'

  workflow_dispatch:

jobs:
  examples:
    runs-on: [self-hosted, linux, gpu]
    container:
      image: ghcr.io/microsoft/agent-lightning/base:latest
      options: --gpus all --ipc=host
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install deps inside the container
        run: ./scripts/setup_stable_gpu.sh
      - name: Freeze dependencies
        run: |
          which python
          which pip
          which uvx
          pip list | tee requirements-freeze.txt
      - name: Upload dependencies artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-python
          path: requirements-freeze.txt
          compression-level: 0
      - name: Calc-X Example
        run: |
          set -ex
          cd examples/calc_x
          gdown --fuzzy https://drive.google.com/file/d/1FQMyKLLd6hP9dw9rfZn1EZOWNvKaDsqw/view
          unzip calc-x-data.zip -d data
          rm calc-x-data.zip
          ../../scripts/restart_ray.sh
          PYTHONUNBUFFERED=1 python calc_agent.py &
          bash train_ci.sh
          pkill -f calc_agent.py || true
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      - name: Cleanup
        run: ./scripts/cleanup.sh
        if: success() || failure()
