name: GPU Test
permissions:
  contents: read
on:
  push:  # for debugging purposes
    branches: [examples-test]
  schedule:
    # Every day at 3 AM UTC+8
    - cron: '0 19 * * *'

  workflow_dispatch:

jobs:
  examples:
    runs-on: [self-hosted, linux, gpu]
    timeout-minutes: 90
    container:
      image: ghcr.io/microsoft/agent-lightning/base:latest
      options: --gpus all --ipc=host --interactive --tty
    steps:
      - name: Check GPU status
        run: nvidia-smi
      - uses: actions/checkout@v4
      - name: Create a virtual environment
        run: python3 -m venv .venv
      - name: Install deps inside the container
        run: |
          . .venv/bin/activate
          ./scripts/setup_stable_gpu.sh
      - name: Freeze dependencies
        run: |
          . .venv/bin/activate
          which python
          which pip
          which uvx
          pip list | tee requirements-freeze.txt
      - name: Upload dependencies artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-python
          path: requirements-freeze.txt
          compression-level: 0
      - name: Prepare Spider dataset
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/spider
          gdown --fuzzy https://drive.google.com/file/d/1oi9J1jZP9TyM35L85CL3qeGWl2jqlnL6/view
          unzip -q spider-data.zip -d data
          rm spider-data.zip
      - name: Prepare Calc-X dataset
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/calc_x
          gdown --fuzzy https://drive.google.com/file/d/1FQMyKLLd6hP9dw9rfZn1EZOWNvKaDsqw/view
          unzip calc-x-data.zip -d data
          rm calc-x-data.zip
      - name: Spider sanity check
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/spider
          python sql_agent.py --trainer.n-workers 1 --trainer.dev true --trainer.max-tasks 5
        env:
          VERL_API_BASE: http://localhost:9999/
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Calc-X MCP sanity check
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/calc_x
          python tests/test_mcp_calculator.py
        env:
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Calc-X sanity check
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/calc_x
          python calc_agent_dev.py
        env:
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Calc-X training
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/calc_x
          ../../scripts/restart_ray.sh
          PYTHONUNBUFFERED=1 python calc_agent.py &
          bash train_ci.sh
          pkill -f calc_agent.py || true
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      - name: Spider training
        run: |
          set -ex
          . .venv/bin/activate
          cd examples/spider
          ../../scripts/restart_ray.sh
          PYTHONUNBUFFERED=1 python sql_agent.py --trainer.n-workers 10 &
          bash train_ci.sh
          pkill -f sql_agent.py || true
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        if: success() || failure()
      - name: Cleanup
        run: ./scripts/cleanup.sh
        if: success() || failure()
