# Pre-defined workflow with workflow_dispatch trigger,
# convenient for testing and debugging.

name: Playground
permissions:
  contents: read
on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Run script
        run: |
          echo "Hello, world!"
