name: CPU Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

  schedule:
    # Every day at noon and midnight
    - cron: '0 0,12 * * *'

jobs:

  test:
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,agent]
      - name: Freeze dependencies
        run: |
          pip list | tee requirements-freeze-${{ matrix.python-version }}.txt
      - name: Upload dependencies artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-python-${{ matrix.python-version }}
          path: requirements-freeze-${{ matrix.python-version }}.txt
          compression-level: 0
      - name: Run tests
        run: |
          pytest -v tests
        env:
          PYTEST_ADDOPTS: "--color=yes"
